graceshoppermmws/graceshoppermmws

.gitignore, .travis.yml, package.json
=> update package.json to reflect name and add secrets file

package.json
---
I uncommented the precommit command in package.json that automatically prettifies the code before committing it. I recommend we use this best practice to avoid having to go back and edit formatting moving forward.
=> issue 10 enable prettify in precommit

server/db/models/user.js
Add isAdmin as boolean field.  Default is false.
Progress on #14
---
Closes #14
=> feat(models): add isAdmin field to User

server/api/index.js, server/api/race.js, server/api/races.js, server/db/models/candidate.js, server/db/models/index.js, server/db/models/race.js
Add race get, get by id, post, put, post candidate by race id, put candidate by raceid and candidateid
closes #5
---
Closes #5
=> feat(api): add race routes

package-lock.json, server/api/index.js, server/api/orders.js
=> Order model #17

server/api/orders.js, server/api/users.js
Add eager loading to user route including orders and clean up order routes
Closes #35
---
=> feat(routes): Add Eager Loading to Routes

script/seed.js, server/api/index.js, server/db/models/candidate.js
Initial seed file created
Progress #34
---
=> feat(seed) Create seed file

script/seed.js, server/api/races.js, server/db/models/race.js
=> Seed file update #38

client/store/candidates.js, client/store/index.js, client/store/order.js, client/store/raceCandidates.js, client/store/raceData.js, client/store/races.js, server/api/candidates.js, server/api/index.js
=> Store race #19

client/app.js, client/components/AddCandidateForm.js, client/components/AllRaces.js, client/components/CandidateForm.js, client/components/ConciseCandidate.js, client/components/Race.js, client/components/RaceForm.js, client/components/SingleCandidate.js, client/components/SingleRace.js, client/components/index.js, client/routes.js, client/store/candidates.js, client/store/index.js, client/store/order.js, client/store/raceCandidates.js, client/store/races.js, script/seed.js, server/api/candidates.js, server/api/index.js, server/api/orders.js, server/api/races.js, server/db/models/candidate.js, server/db/models/index.js, server/db/models/race.js
Comment out Race, Candidate, Order related files
Closes #52
---
Closes #52
=> bugfix(clean-up) Edit for MVP

server/db/models/index.js, server/db/models/product.js
=> feat(newModel): added product model and changed associations

script/seed.js, server/db/models/index.js, server/db/models/order.js, server/db/models/product.js
Update seed file and fix legacy mentions of candidate
Closes #56
---
Closes #56
=> feat(seed) Update seed file

server/api/index.js, server/api/orders.js, server/api/products.js
=> Rewrite routes #54

script/seed.js
Adding a few users to the seed file
Closes seed#72
---
closes #72
=> feat(seed): Adding admin users

client/components/AddProduct.js, client/components/AllProducts.js, client/components/EditProduct.js, client/components/ProductForm.js, client/components/SingleProduct.js
Add Admin vs. Shopper filter from store to react component
Progress on #77
---
=> feat(component): Update Edit and Add Admin vs. Shopper View

client/components/navbar.js, public/style.css
=> feat(navBar): add all cand link to nav bar and add a little color

client/store/orders.js, client/store/products.js, script/seed.js, server/api/orders.js, server/api/products.js, server/db/models/index.js, server/db/models/order.js, server/db/models/orderproduct.js
---
Putting the minimum in minimum closes #70
=> Order route inquiry #70

client/components/user-home.js, server/auth/google.js
Finish passport config and user view default to AllProducts
Closes passport#75, #91 
---
Closes #91
=> feat(passport): passport and userview to allProducts

client/components/AllProducts.js, client/components/Cart.js, client/components/Order.js, client/store/orders.js, server/api/products.js, server/api/users.js
=> Cart user route #105

.travis.yml
=> Deployment #106

client/components/AllProducts.js, server/api/users.js, server/auth/index.js
Add cart on sign up
Progress on #85
---
=> feat(cart): Add cart on sign up

client/components/AllProducts.js, client/components/Cart.js
Add local storage for cart for unauthorized user
Progrss on #116
---
=> feat(cart): Add cart for unauthorized user

client/components/AllProducts.js, client/components/Cart.js, client/components/Product.js, client/components/ProductForm.js, client/components/SingleProduct.js
=> feat(single view): Add single buy to single view

client/components/AddProduct.js, client/components/AllProducts.js, client/components/Cart.js, client/components/CheckoutForm.js, client/components/SingleProduct.js, package-lock.json, package.json, public/index.html
=> Toast notifications #144

client/components/AllProducts.js, client/components/Product.js, client/components/SingleProduct.js, client/store/orders.js, package-lock.json, server/api/users.js
=> Set quantity #112

client/components/Cart.js
=> Promo code #152

client/components/Cart.js, client/components/SingleProduct.js, client/routes.js, server/api/users.js
=> Bugfix cart #158

client/store/orders.js
=> (fix) remove item from cart

client/components/Cart.js, client/components/Order.js
=> Connect discount #163

client/components/Cart.js, client/store/orders.js, server/api/orders.js, server/api/users.js
=> Discount #165

client/store/products.spec.js, server/api/products.spec.js
=> Write tests orders #166

client/components/Cart.js
=> fix(cart): Hide Promo Code from Logged Out users

client/components/Order.js
=> fix(orders): Display subtotal for past and all orders

client/routes.js, server/auth/google.js
=> Google user cart

script/seed.js
=> feat(seed): add more products, users, and photos

client/app.js, client/routes.js, client/store/orders.js, client/store/products.js, client/store/products.spec.js, server/api/orders.js, server/api/products.js, server/api/stripe.js, server/api/users.js
=> Api security #180
